"""Canonical Pydantic model for workflow_context.json.

v2.0: Strengthened validation — script-generated fields are required,
      agent-enrichment fields have type validation with empty defaults.
"""

from typing import Optional

from pydantic import BaseModel, Field

from .base import ALLOW_EXTRA


class PreviousStats(BaseModel):
    model_config = ALLOW_EXTRA

    papers_analyzed: Optional[int] = None
    cases_collected: Optional[int] = None
    variants_identified: Optional[int] = None
    total_uos: Optional[int] = None
    qc_checkpoints: Optional[int] = None
    confidence_score: Optional[float] = None


class QualityMetrics(BaseModel):
    model_config = ALLOW_EXTRA

    target_papers: Optional[str] = None
    target_cases: Optional[str] = None
    target_variants: Optional[str] = None
    min_confidence: Optional[float] = None


class WorkflowContext(BaseModel):
    model_config = ALLOW_EXTRA

    # Required — deterministically generated by resolve_workflow.py
    # Gate 1 assert checks enforce non-null for new compositions.
    workflow_id: str = Field(pattern=r"^W[BTDL]\d{3}$")
    workflow_name: str
    category: str
    domain: str
    description: str
    mode: str = "new"
    composition_date: str = ""
    version: int | float = 1.0

    # Script-generated, may be empty depending on data source
    domain_keywords: list[str] = Field(default_factory=list)
    search_terms: list[str] = Field(default_factory=list)

    # Update-mode fields (previous_version may be "unknown" in legacy data)
    previous_version: Optional[int | float | str] = None
    target_version: Optional[int | float] = None
    backup_path: Optional[str] = None
    previous_stats: Optional[PreviousStats] = None

    # Agent-enrichment fields (type-validated, default to empty)
    upstream_workflows: list[str] = Field(default_factory=list)
    downstream_workflows: list[str] = Field(default_factory=list)
    target_organisms: list[str] = Field(default_factory=list)
    key_techniques: list[str] = Field(default_factory=list)
    uo_candidates: list[str] = Field(default_factory=list)
    quality_metrics: Optional[QualityMetrics] = None
